### ISSUE TITLE
Can't create 1:n relation alongside with m:n relation

### ISSUE THREAD

**Issue by ignatif** [prisma/migrate#175]
hey guys. got a question.
so i got two tables: User and Community. I've set many-to-many relationship between them. Community has followers (User[]) and User has following communities (Community[])
```
model User {
  id          String  @default(cuid()) @id
  email       String  @unique
  name        String?
  communities Community[]
}

model Community {
  id          String   @default(cuid()) @id
  name        String
  followers   User[]
}
```
I'm now trying to also add one-to-many relationship: so each Community has an author (User)
```
model Community {
  id        String   @default(cuid()) @id
  name      String
  followers User[]
  author    User?
}
```
But when executing command `npx prisma2 lift save --name 'add community author'` i get the following error

```
 ERROR  Oops, an unexpected error occured!
Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREATE TABLE IF NOT EXISTS \"lift\".\"_Migration\" (\"revision\" INTEGER NO
T NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"data
base_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
thread 'tokio-runtime-worker-1' panicked at 'Failed lookup of model or field during internal processing. This means that the internal representation was mutated incorrectly.', src/libcore/option.rs:1166:5
stack backtrace:
 ERROR  Oops, an unexpected error occured!
Error in migration engine: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:40] &sql_str = "CREATE TABLE IF NOT EXISTS \"lift\".\"_Migration\" (\"revision\" INTEGER NO
T NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"data
base_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
thread 'tokio-runtime-worker-1' panicked at 'Failed lookup of model or field during internal processing. This means that the internal representation was mutated incorrectly.', src/libcore/option.rs:1166:5
stack backtrace:
```

anyone can help?

**Comment by pantharshit00** [comment]
You will need to add `@relation` directives in order to disambiguit the relations:

```groovy
model User {
  id          String      @default(cuid()) @id
  email       String      @unique
  name        String?
  communities Community[] @relation(name: "UserFollower")
  posts       Community[] @relation(name: "UserAuthor")
}

model Community {
  id        String @default(cuid()) @id
  name      String
  followers User[] @relation(name: "UserFollower")
  author    User?  @relation(name: "UserAuthor")
}
```

But I do think we can improve the error message

**Comment by ignatif** [comment]
or should i open it?

**Comment by pantharshit00** [comment]
I would keep this open so that we can consider fixing the error message 🙂

**Comment by janpio** [comment]
Thsi changed completely, so we are closing this for now 🚀
