### ISSUE TITLE
Error in migration engine.

### ISSUE THREAD

**Issue by shagoto-bhakat** [prisma/migrate#280]
```
Reason: [/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.4/src/io/driver/mod.rs:243:21] no current reactor
 at ChildProcess.<anonymous> (C:\Users\***
```

```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean  @default(false)
  title     String
  content   String?
  author    User?
}

model User {
  id       String  @default(cuid()) @id
  email    String  @unique
  password String
  name     String?
  posts    Post[]
}
```

```
\***\***\***\node_modules\prisma2\build\index.js:172040:35)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
`´`

**Comment by pantharshit00** [comment]
Hi,

Can you please try this again? I think this has been already fixed in https://github.com/prisma/prisma2/issues/1395
