### ISSUE TITLE
ENOENT `schema.prisma`

### ISSUE THREAD

**Issue by scriptcoded** [prisma/migrate#334]
Good morning (or good wheneveryoureadthis),

I recently upgraded to 020, and since then I can't run migrations. Here is my log:

```
$ prisma2 migrate save --experimental
 ERROR  Oops, an unexpected error occured!
Error in migration engine.
Reason: [src/libcore/result.rs:1165:5] Error parsing the migration steps: Error("missing field `tag`", line: 1
, column: 46)

Please create an issue in the lift repo with
your `schema.prisma` and the prisma2 command you tried to use 🙏:
https://github.com/prisma/lift/issues/new

Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

┌─ Submit error report ────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                          │
│ ⠴ Submitting error report                                                                                │
│   No             Don't send error report                                                                 │
│                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
/home/scriptcoded/.nvm/versions/node/v12.11.1/lib/node_modules/prisma2/build/index.js:159388
        throw ex;
        ^

Error: ENOENT: no such file or directory, open 'schema.prisma'
Emitted 'error' event on Archiver instance at:
    at Archiver.onerror (/home/scriptcoded/.nvm/versions/node/v12.11.1/lib/node_modules/prisma2/build/index.js:32048:52)
    at Archiver.emit (events.js:210:5)
    at Archiver.EventEmitter.emit (domain.js:476:20)
    at Archiver.<anonymous> (/home/scriptcoded/.nvm/versions/node/v12.11.1/lib/node_modules/prisma2/build/index.js:73826:12)
    at module.exports.6148.module.exports.handleStuff (/home/scriptcoded/.nvm/versions/node/v12.11.1/lib/node_modules/prisma2/build/index.js:103850:5)
    at Object.onceWrapper (events.js:299:28)
    at DeflateCRC32Stream.emit (events.js:215:7)
    at DeflateCRC32Stream.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'schema.prisma'
}
```

When not passing in the environment variables used in my schema Migrate complains about that, so I think it'd be safe to assume that somewhere down the line Migrate actually reads the file.

This also happens when running `migrate up`

Running Prisma `prisma2@2.0.0-preview020.3, binary version: 45dd3493ff2fd09b5a8cdf697de276e368f7ebee`

**Comment by scriptcoded** [comment]
Quick update,
I'm thinking that this might be related to #333 and that perhaps the Wrong version of Prisma is used? I'm getting old docs when running just `prisma2`, even though `prisma2 -v` gives the right version:

```
◭ Prisma makes your data easy (https://prisma.io)

Usage

  $ prisma2 [command]

Commands

            init   Setup Prisma for your app
      introspect   Get the datamodel of your database
        generate   Generate Prisma Client
```

**Comment by scriptcoded** [comment]
Quick update,
I'm thinking that this might be related to #333 and that perhaps the Wrong version of Prisma is used? I'm getting wrong names again when running against a non-existent DB:

```
$ prisma2 migrate up --create-db --experimental
🏋️‍ lift up

All migrations are already applied
```

**Comment by scriptcoded** [comment]
Another update. I managed to get it working by completely removing the database and not only creating new schemes. I don't know if this is of any interest to you still, but there you go. Closing this for now.
