### ISSUE TITLE
I have problem with migration [report id 6373]

### ISSUE THREAD

**Issue by gustawdaniel** [prisma/migrate#461]
I created the following schema

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator prisma_client {
  provider = "prisma-client-js"
}

model Visit {
  id         Int    @id @default(autoincrement())
  created_at String
}
```

I trying to create migration

```
npx prisma migrate save --experimental
```

And I have error:

```
Environment variables loaded from ./prisma/.env
The format of migrations changed, the saved migrations are no longer valid. To solve this problem, pl
ease follow the steps at: https://pris.ly/d/migrate#troubleshooting
We successfully received the error report
To help us even more, please create an issue at https://github.com/prisma/prisma/issues/new
mentioning the report id 6373.
```

**Comment by gustawdaniel** [comment]
I fixed by switching to flow described there:

> https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql-typescript-mysql

1) Create database tables with SQL
2) Introspect your database with Prisma
3) Install and generate Prisma Client

**Comment by pantharshit00** [comment]
The error report also has the same stack trace:
```
Error: The format of migrations changed, the saved migrations are no longer valid. To solve this problem, please follow the steps at: https://pris.ly/d/migrate#troubleshooting
    at Object.<anonymous> (/home/daniel/pro/ocr/backend/node_modules/@prisma/cli/build/index.js:2:11567)
    at MigrateEngine.handleResponse (/home/daniel/pro/ocr/backend/node_modules/@prisma/cli/build/index.js:2:9775)
    at LineStream.<anonymous> (/home/daniel/pro/ocr/backend/node_modules/@prisma/cli/build/index.js:2:11232)
    at LineStream.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/home/daniel/pro/ocr/backend/node_modules/@prisma/cli/build/index.js:2:465240)
    at LineStream._transform (/home/daniel/pro/ocr/backend/node_modules/@prisma/cli/build/index.js:2:465061)
```

Resetting migrations is the correct solution here
