### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: type "MembershipRole" already exists 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#509]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8632 
OS: `x64 darwin 18.7.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: type "MembershipRole" already exists
   0: migration_core::api::ApplyMigration
           with migration_id="20200707200209-init"
             at migration-engine/core/src/api.rs:77)
    at Object.registerCallback (/Users/raffa/Repositories/rifiutoo-backend/app/node_modules/@prisma/cli/build/index.js:2:2371074)
    at MigrateEngine.handleResponse (/Users/raffa/Repositories/rifiutoo-backend/app/node_modules/@prisma/cli/build/index.js:2:2369282)
    at LineStream.a.default.on.e (/Users/raffa/Repositories/rifiutoo-backend/app/node_modules/@prisma/cli/build/index.js:2:2370739)
    at LineStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:151:32)
    at LineStream._pushBuffer (/Users/raffa/Repositories/rifiutoo-backend/app/node_modules/@prisma/cli/build/index.js:2:2062886)
    at LineStream._transform (/Users/raffa/Repositories/rifiutoo-backend/app/node_modules/@prisma/cli/build/index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: type "MembershipRole" already exists
   0: migration_core::api::ApplyMigration
           with migration_id="20200707200209-init"
             at migration-engine/core/src/api.rs:77)
```

**Comment by divyenduz** [comment]
From the steps, it looks like they were trying to convert an enum to a model

```
"0": {
        "tag": "DeleteEnum",
        "enum": "MembershipRole"
      },
      "1": {
        "tag": "CreateModel",
        "model": "MembershipRole"
      },
```

**Comment by tomhoule** [comment]
Oh that's a really interesting case I hadn't thought about.

**Comment by albertoperdomo** [comment]
@tomhoule to reproduce
