### ISSUE TITLE
Error: Failure during a migration command: The migration produced an invalid schema. 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#512]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8699 
OS: `x64 win32 10.0.19041`

JS Stacktrace:
```
Error: Failure during a migration command: The migration produced an invalid schema.
Datamodel error in schema that could not be rendered. Error validating model "ThirdParty": The id definition refers to the optional fields orgId. Id definitions must reference only required fields.
    at Object.<anonymous> (D:\Adar\Projects\safebase\qnr-server\node_modules\@prisma\cli\build\index.js:2:2371074)
    at MigrateEngine.handleResponse (D:\Adar\Projects\safebase\qnr-server\node_modules\@prisma\cli\build\index.js:2:2369282)
    at LineStream.<anonymous> (D:\Adar\Projects\safebase\qnr-server\node_modules\@prisma\cli\build\index.js:2:2370739)
    at LineStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at LineStream.Readable.push (_stream_readable.js:217:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (D:\Adar\Projects\safebase\qnr-server\node_modules\@prisma\cli\build\index.js:2:2062886)
    at LineStream._transform (D:\Adar\Projects\safebase\qnr-server\node_modules\@prisma\cli\build\index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: The migration produced an invalid schema.
Datamodel error in schema that could not be rendered. Error validating model "ThirdParty": The id definition refers to the optional fields orgId. Id definitions must reference only required fields.
```

**Comment by tomhoule** [comment]
This is an issue with experimental migrate that can't occur in preview migrate.
