### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42000 (1061): Duplicate key name 'Costs.QuoteId'' 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#515]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8738 
OS: `x64 linux 4.15.0-109-generic`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42000 (1061): Duplicate key name 'Costs.QuoteId''
   0: migration_core::api::ApplyMigration
           with migration_id="20200709140234-finders-paid-at"
             at migration-engine/core/src/api.rs:77)
    at Object.<anonymous> (/usr/local/lib/node_modules/@prisma/cli/build/index.js:2:2371074)
    at MigrateEngine.handleResponse (/usr/local/lib/node_modules/@prisma/cli/build/index.js:2:2369282)
    at LineStream.<anonymous> (/usr/local/lib/node_modules/@prisma/cli/build/index.js:2:2370739)
    at LineStream.emit (events.js:203:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at LineStream.Readable.push (_stream_readable.js:210:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/usr/local/lib/node_modules/@prisma/cli/build/index.js:2:2062886)
    at LineStream._transform (/usr/local/lib/node_modules/@prisma/cli/build/index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42000 (1061): Duplicate key name 'Costs.QuoteId''
   0: migration_core::api::ApplyMigration
           with migration_id="20200709140234-finders-paid-at"
             at migration-engine/core/src/api.rs:77)
```

**Comment by tomhoule** [comment]
It looks like a collision between an index on the FK and a unique index, but I haven't been able to reproduce the crash locally.

**Comment by tomhoule** [comment]
We used to generate potentially ambiguous names, but this was changed, so as far as I can tell, this should not happen anymore.
