### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/sql-schema-describer/src/postgres.rs:125:23] could not get columns 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#517]
Command: `prisma migrate save --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8742 
OS: `x64 linux 4.4.0-19041-Microsoft`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/postgres.rs:125:23] could not get columns

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/home/awoo/.nvm/versions/node/v14.5.0/lib/node_modules/@prisma/cli/build/index.js:2:2370192)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
[libs/sql-schema-describer/src/postgres.rs:125:23] could not get columns
```

**Comment by tomhoule** [comment]
This is probably fixed (missing permissions handling).. We return better errors now. The issue is not actionable.
