### ISSUE TITLE
Error: Failure during a migration command: Generic error. (error: The source sqlite does not exist in this Schema. It is not possible to delete it.) 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#547]
Command: `prisma migrate up --experimental`
Version: `2.3.0`
Binary Version: `e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e`
Report: https://prisma-errors.netlify.app/report/9772 
OS: `x64 linux 5.3.0-61-generic`

JS Stacktrace:
```
Error: Failure during a migration command: Generic error. (error: The source sqlite does not exist in this Schema. It is not possible to delete it.)
    at Object.<anonymous> (/home/alexandre/www/MailAnalyz/node_modules/@prisma/cli/build/index.js:2:2135004)
    at MigrateEngine.handleResponse (/home/alexandre/www/MailAnalyz/node_modules/@prisma/cli/build/index.js:2:2133212)
    at LineStream.<anonymous> (/home/alexandre/www/MailAnalyz/node_modules/@prisma/cli/build/index.js:2:2134669)
    at LineStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at LineStream.Readable.push (_stream_readable.js:217:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/home/alexandre/www/MailAnalyz/node_modules/@prisma/cli/build/index.js:2:1819384)
    at LineStream._transform (/home/alexandre/www/MailAnalyz/node_modules/@prisma/cli/build/index.js:2:1819205)
```

Rust Stacktrace:
```
Failure during a migration command: Generic error. (error: The source sqlite does not exist in this Schema. It is not possible to delete it.)
```

**Comment by tomhoule** [comment]
This is not relevant starting with 2.13.0
