### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:127:34] called `Result::unwrap()` on an `Err` value: Error { kind: UniqueConstraintViolation { constraint: Fields(["revision"]) }, original_code: Some("23505"), original_message: Some("Key (revision)=(2) already exists.") } 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#560]
Command: `prisma migrate up --experimental`
Version: `2.5.0`
Binary Version: `9a670138b1db276001d785a2adcba1584c869d24`
Report: https://prisma-errors.netlify.app/report/10382 
OS: `x64 linux 5.4.0-42-generic`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:127:34] called `Result::unwrap()` on an `Err` value: Error { kind: UniqueConstraintViolation { constraint: Fields(["revision"]) }, original_code: Some("23505"), original_message: Some("Key (revision)=(2) already exists.") }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/home/char1zart/projects/mobbackend/node_modules/@prisma/cli/build/index.js:2:2144563)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:127:34] called `Result::unwrap()` on an `Err` value: Error { kind: UniqueConstraintViolation { constraint: Fields(["revision"]) }, original_code: Some("23505"), original_message: Some("Key (revision)=(2) already exists.") }
```

**Comment by tomhoule** [comment]
That code is gone since 2.13.0
