### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: current transaction is aborted, commands ignored until end of transaction block 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#562]
Command: `prisma migrate up --experimental`
Version: `2.5.0`
Binary Version: `9a670138b1db276001d785a2adcba1584c869d24`
Report: https://prisma-errors.netlify.app/report/10466 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: current transaction is aborted, commands ignored until end of transaction block
   0: migration_core::api::ApplyMigration
           with migration_id="20200820144808-initial"
             at migration-engine/core/src/api.rs:79)
    at Object.<anonymous> (/Users/alizahid/Desktop/apps/~paisa/api/node_modules/@prisma/cli/build/index.js:2:2145445)
    at MigrateEngine.handleResponse (/Users/alizahid/Desktop/apps/~paisa/api/node_modules/@prisma/cli/build/index.js:2:2143653)
    at LineStream.<anonymous> (/Users/alizahid/Desktop/apps/~paisa/api/node_modules/@prisma/cli/build/index.js:2:2145110)
    at LineStream.emit (events.js:314:20)
    at LineStream.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at LineStream.Readable.push (_stream_readable.js:218:10)
    at LineStream.Transform.push (_stream_transform.js:166:32)
    at LineStream._pushBuffer (/Users/alizahid/Desktop/apps/~paisa/api/node_modules/@prisma/cli/build/index.js:2:1813582)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: current transaction is aborted, commands ignored until end of transaction block
   0: migration_core::api::ApplyMigration
           with migration_id="20200820144808-initial"
             at migration-engine/core/src/api.rs:79)
```

**Comment by tomhoule** [comment]
This should be fixed — we do return early whenever an error occurs on migration application now.
