### ISSUE TITLE
Error: Cannot read property 'file' of undefined when running ‘up`

### ISSUE THREAD

**Issue by FinnFrotscher** [prisma/migrate#586]
```
$ source .env.database && prisma migrate up --experimental --schema src/services/prisma/schema.prisma

  prisma Environment variables not loaded (--schema was provided) +0ms
Error: TypeError: Cannot read property 'file' of undefined
    at /Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2938453
    at Array.map (<anonymous>)
    at Migrate.getLocalMigrations (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2938154)
    at async Migrate.getMigrationsToApply (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2939488)
    at async Migrate.up (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2933915)
    at async MigrateUp.parse (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:1866594)
    at async main (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:1480086)
error Command failed with exit code 1.
```

```
$ yarn prisma:version                                                                ...kages/backend-api
@prisma/cli          : 2.6.2
Current platform     : darwin
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
✨  Done in 1.57s.
```

**Comment by janpio** [comment]
Unrelated: Do you always get the `  prisma Error: Could not find schema.prisma` error on `prisma --version`? If so, could you _also_ create an issue about that please? SHould not happen.

**Comment by FinnFrotscher** [comment]
any sugestion?

**Comment by FinnFrotscher** [comment]
?

**Comment by FinnFrotscher** [comment]
solved: the steps.json was missing. a more expressive error message would have saved us days. also, please be more verbose when handling issues.

**Comment by timi-codes** [comment]
@FinnFrotscher Please can you provide an explanation on how you solved this. Where can I get more information about steps.json

**Comment by FinnFrotscher** [comment]
steps.json is located inside each of the migration steps.
it went missing for us in a git merge.
we fixed it by fixing the git commit.

**Comment by timi-codes** [comment]
Thanks @FinnFrotscher . This actually fixed it for me as well
