### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:104:9] internal error: entered unreachable code: AddForeignKey on SQLite 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#594]
Command: `prisma migrate save --schema=/Users/user2/code/spkb/db/schema.prisma --create-db --experimental`
Version: `2.7.1`
Binary Version: `5c2ad460cf4fe8c9330e6640b266c046542c8b6a`
Report: https://prisma-errors.netlify.app/report/11354 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:104:9] internal error: entered unreachable code: AddForeignKey on SQLite

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/user2/code/spkb/node_modules/@prisma/cli/build/index.js:2:2163910)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:104:9] internal error: entered unreachable code: AddForeignKey on SQLite
```

**Comment by tomhoule** [comment]
Pretty sure this was fixed. Let's close the issue.
