### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine\connectors\sql-migration-connector\src\sql_migration_persistence.rs:102:34] called `Result::unwrap()` on an `Err` value: ConnectorError { user_facing_error: None, kind: Timeout, context: SpanTrace [{ target: "migration_core::api", name: "ApplyMigration", fields: "migration_id=\"20201001140258-access-token-to-token\"", file: "migration-engine\\core\\src\\api.rs", line: 94 }] } 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#605]
Command: `prisma migrate --experimental up`
Version: `2.8.0`
Binary Version: `e6c9b4b2b7fa162d0d459d1863321f547498fcfe`
Report: https://prisma-errors.netlify.app/report/11562 
OS: `x64 win32 10.0.19042`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\connectors\sql-migration-connector\src\sql_migration_persistence.rs:102:34] called `Result::unwrap()` on an `Err` value: ConnectorError { user_facing_error: None, kind: Timeout, context: SpanTrace [{ target: "migration_core::api", name: "ApplyMigration", fields: "migration_id=\"20201001140258-access-token-to-token\"", file: "migration-engine\\core\\src\\api.rs", line: 94 }] }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (D:\projects\anphat-api\node_modules\@prisma\cli\build\index.js:2:2230694)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[migration-engine\connectors\sql-migration-connector\src\sql_migration_persistence.rs:102:34] called `Result::unwrap()` on an `Err` value: ConnectorError { user_facing_error: None, kind: Timeout, context: SpanTrace [{ target: "migration_core::api", name: "ApplyMigration", fields: "migration_id=\"20201001140258-access-token-to-token\"", file: "migration-engine\\core\\src\\api.rs", line: 94 }] }
```

**Comment by albertoperdomo** [comment]
Can you please repro @pantharshit00 ?

**Comment by tomhoule** [comment]
This is specific to experimental migrate, it should no longer happen on preview migrate. Thanks!
