### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#620]
Command: `prisma migrate up --experimental`
Version: `2.9.0`
Binary Version: `369b3694b7edb869fad14827a33ad3f3f49bbc20`
Report: https://prisma-errors.netlify.app/report/11672 
OS: `x64 win32 10.0.18363`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (C:\Users\abdel$\Documents\shopify_back_end\prod\prisma2.0\node_modules\@prisma\cli\build\index.js:412:153)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\d023a05\src\connector\mysql\error.rs:129:43] index out of bounds: the len is 1 but the index is 1
```

**Comment by pimeys** [comment]
There is no repro yet, confirmed with @divyenduz that there's been only one accidental repro, that couldn't be repeated.

Tested now:
- Prisma 2.10.0
- MySQL 8.0.21
- MySQL 5.7.31-1debian10
- MariaDB 10.5.6-MariaDB-1:10.5.6+maria~focal

**Comment by RinatGumarov** [comment]
Have same problem with database in cloud. Migrations works well on local db.

**Comment by tomhoule** [comment]
@RinatGumarov can you elaborate on your setup? Which cloud database provider? It would also be helpful if it's possible to share your prisma schema, and maybe even the migrations folder.

**Comment by RinatGumarov** [comment]
> @RinatGumarov can you elaborate on your setup? Which cloud database provider? It would also be helpful if it's possible to share your prisma schema, and maybe even the migrations folder.

Yes, sure. It is ManagedService for PostgreSQL on Yandex.Cloud. Here you can find migrations and schema - https://github.com/RinatGumarov/prisma-issue

**Comment by tomhoule** [comment]
Thanks a lot for the context, this is going to help. I put a label on the issue so we don't miss it in the next migrations team planning meeting :)

**Comment by cudba** [comment]
i have a similar error trying to run migrations against a postgres database in aws, this is running from CI since the database is not reachable from outside.

its just 1 basic table

```bash
Error: Migration engine error:
--
101 | Nov 06 12:58:05.530  INFO migration_engine: Starting migration engine CLI 
git_hash="7d0087eadc7265e12d4b8d8c3516b02c4c965111"
102 | {"is_panic":true,"message":"[/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/4d8fcae/src/connector/postgres/error.rs:121:28] index out of bounds: the len is 1 but the index is 1","backtrace":"   0: user_facing_errors::Error::new_in_panic_hook\n   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}\n   2: std::panicking::rust_panic_with_hook\n             at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530:17\n   3: rust_begin_unwind\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437:5\n   4: core::panicking::panic_fmt\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85:14\n   5: core::panicking::panic_bounds_check\n             at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:62:5\n   6: quaint::connector::postgres::error::<impl core::convert::From<tokio_postgres::error::Error> for quaint::error::Error>::from\n   7: quaint::single::Quaint::new::{{closure}}\n   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n  10: migration_engine::commands::Cli::run_inner::{{closure}}\n  11: migration_engine::main::{{closure}}\n  12: tokio::runtime::thread_pool::ThreadPool::block_on\n  13: tokio::runtime::context::enter\n  14: tokio::runtime::handle::Handle::enter\n  15: migration_engine::main\n  16: std::rt::lang_start::{{closure}}\n  17: std::rt::lang_start_internal::{{closure}}\n             at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52:13\n      std::panicking::try::do_call\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348:40\n      std::panicking::try\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325:15\n      std::panic::catch_unwind\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394:14\n      std::rt::lang_start_internal\n             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51:25\n  18: main\n  19: __libc_start_main\n  20: <unknown>\n"}
```

its working against local database, gonna try and do some more investigation
