### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator.rs:302:14] internal error: entered unreachable code: enum_column_type on flavour that does not support enums 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#631]
Command: `prisma migrate up --experimental`
Version: `2.10.0`
Binary Version: `af1ae11a423edfb5d24092a85be11fa77c5e499c`
Report: https://prisma-errors.netlify.app/report/11886 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator.rs:302:14] internal error: entered unreachable code: enum_column_type on flavour that does not support enums

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/leo/Development/Jellow/messaging-system-service-graphql/node_modules/@prisma/cli/build/index.js:418:153)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator.rs:302:14] internal error: entered unreachable code: enum_column_type on flavour that does not support enums
```

**Comment by divyenduz** [comment]
This is multi-provider datasources and that is being deprecated. Won't fix.
