### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/sql-schema-describer/src/walkers.rs:329:18] foreign key references unknown table: "Game" 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#632]
Command: `prisma migrate save --experimental`
Version: `2.10.0`
Binary Version: `af1ae11a423edfb5d24092a85be11fa77c5e499c`
Report: https://prisma-errors.netlify.app/report/11820 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:329:18] foreign key references unknown table: "Game"

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/larry-park/.config/yarn/global/node_modules/@prisma/cli/build/index.js:418:153)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
[libs/sql-schema-describer/src/walkers.rs:329:18] foreign key references unknown table: "Game"
```

**Comment by tomhoule** [comment]
This is on MySQL. Not closing this as duplicate yet.
