### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:91:66] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("SQLite database is busy"), original_code: Some("5"), original_message: Some("database is locked") }, connection_info: Sqlite { file_path: "dev.db", db_name: "quaint" } } 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#633]
Command: `prisma migrate up --experimental`
Version: `2.10.0`
Binary Version: `af1ae11a423edfb5d24092a85be11fa77c5e499c`
Report: https://prisma-errors.netlify.app/report/11847 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:91:66] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("SQLite database is busy"), original_code: Some("5"), original_message: Some("database is locked") }, connection_info: Sqlite { file_path: "dev.db", db_name: "quaint" } }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/mortenpetersen/Downloads/UBFA/node_modules/@prisma/cli/build/index.js:418:153)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:91:66] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("SQLite database is busy"), original_code: Some("5"), original_message: Some("database is locked") }, connection_info: Sqlite { file_path: "dev.db", db_name: "quaint" } }
```

**Comment by divyenduz** [comment]
Issue for better error message

**Comment by tomhoule** [comment]
I think the better error message is already implemented. Closing this issue.
