### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by chrisui** [prisma/migrate#77]
A couple of suggestions after my fairly painful first go with using lift.

In this first one it'd be great to know what the url it thinks I have passed is. In this specific case my url is supposed to be env() but I'm not quite sure how to debug!

```
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'the url for postgres must start with 'postgresql:'', migration-engine/connectors/sql-migration-connector/src/lib.rs:102:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
   6: sql_migration_connector::SqlMigrationConnector::new
   7: migration_core::connector_loader::load_connector
   8: migration_core::migration_engine::MigrationEngine::init
   9: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  10: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  11: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  12: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  15: futures::task_impl::std::set
  16: std::thread::local::LocalKey<T>::with
  17: futures::future::Future::wait
  18: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  19: migration_core::rpc_api::RpcApi::handle
  20: migration_engine::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  24: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  25: main
  26: __libc_start_main
  27: _start
```

In this it'd be great to know exactly where in my definition is the bad syntax. In this case it was use of single quotes rather than double. As a bonus here I copied the code straight from the lift homepage [examples](https://lift.prisma.io/)!

```
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'loading the connector failed.: DataModelErrors { code: 1001, errors: ["Unexpected token. Expected one of: expression."] }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: migration_core::migration_engine::MigrationEngine::init
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  13: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: futures::task_impl::std::set
  17: std::thread::local::LocalKey<T>::with
  18: futures::future::Future::wait
  19: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  20: migration_core::rpc_api::RpcApi::handle
  21: migration_engine::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  25: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  26: main
  27: __libc_start_main
  28: _start
```

**Comment by chrisui** [comment]
I'm also a bit mythed by the first issue as I've hard coded the url and get the same error.

```
datasource pg {
  provider = "postgresql"
  url      = "postgres://prisma:prisma@db:5432/db"
}
```

```
Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'the url for postgres must start with 'postgresql:'', migration-engine/connectors/sql-migration-connector/src/lib.rs:102:17
```

**Comment by pantharshit00** [comment]
We are working on an error handling spec. Please have a look here: https://github.com/prisma/specs/tree/master/errors
